const mongoose = require("mongoose"),
Schema = mongoose.Schema,
config = require("../config.js");
module.exports = mongoose.model("acctime", new Schema({
    email: { type: String, default: '' },
    id: { type: Number, default: 0 },
    user: { type: String, default: '' },
    pass: { type: String, default: '' },
    date: { type: String, default: '' },
    balance: { type: Number, default: 0 },
    avatar: { type: String, default: `${config.dashboard.cdn}/scpsl.store/users/avatars/unknow.png` },
    banner: { type: String, default: '' },
    name: { type: String, default: '' },
    clan: { type: String, default: '' },
    style: { type: Number, default: 0 },
    steam: { type: String, default: '' },
    discord: { type: String, default: '' },
    prefix: { type: String, default: '' },
    achievements: { type: Array, default: [] },
    ips: { type: Array, default: [] },

    ip: { type: String, default: '' },
    cookie: { type: String, default: '' },
    passKey: { type: String, default: '' },
    time: { type: String, default: 'Нет данных' },

    kicks: { type: Number, default: 0 },
    bans: { type: Number, default: 0 },
    mn: { type: Number, default: 0 },//#нарушения-игроков
    adminmin: { type: Number, default: 0 },
    ytr: { type: Boolean, default: false },
    sr: { type: Boolean, default: false },
    hr: { type: Boolean, default: false },
    ghr: { type: Boolean, default: false },
    ar: { type: Boolean, default: false },
    gar: { type: Boolean, default: false },
    asr: { type: Boolean, default: false },
    dcr: { type: Boolean, default: false },
    or: { type: Boolean, default: false },
    antiraider: { type: Boolean, default: false },
    asrc: { type: Number, default: 0 },
    asrcm: { type: Number, default: 0 },
    asrch: { type: Array, default: [] },
    warnings: { type: Number, default: 0 },
}));